AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - '*.gemspec'
    - 'vendor/bundle/**/*'
    - 'test/**/*'
  SuggestExtensions: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/ClassVars:
  Enabled: false

Metrics/MethodLength:
  Enabled: false